### ISSUE TITLE
Add support for HTTP Basic Auth

### ISSUE THREAD

**Issue by SRChiP** [Bartuzen/qBitController#102]
### Describe your suggested feature

My qbittorrent server is behind a HTTP Basic Auth nginx reverse proxy. I would love to able to be connect to it without reducing the security.

I already tried to login by setting the hostname an user:pass@host but it didn't work. The app showed an "Unknown login response: null" error

**Comment by Bartuzen** [comment]
This feature already exists. To access it, navigate to edit server screen and press advanced settings in the toolbar.
