### ISSUE TITLE
Show peer speeds in torrent properties page

### ISSUE THREAD

**Issue by Pentaphon** [Bartuzen/qBitController#106]
### Describe your suggested feature

Please show the peer speeds in the torrent properties page to match with what we can see on the original WebUI.

**Comment by Bartuzen** [comment]
You can already click on a peer to view its download and upload speeds. Or are you referring to something else?

**Comment by Pentaphon** [comment]
> You can already click on a peer to view its download and upload speeds. Or are you referring to something else?

Can we have it showing without tapping it? Or is that not possible?

**Comment by Bartuzen** [comment]
I suppose I can place it under the flag icon.

**Comment by Pentaphon** [comment]
> I suppose I can place it under the flag icon.

Please do! Thanks!
