### ISSUE TITLE
Adding a torrent no longer respect default management mode

### ISSUE THREAD

**Issue by Matth7878** [Bartuzen/qBitController#108]
### Bug description

I don't know when it changed but now when adding a torrent it is always on manual if management mode is set to default.
It does not respect my default which is set to automatic and I need to explicitly change it for each torrent I am adding.

### qBitController version

0.8.2

### qBittorrent version

4.6.0

### Android version

10

**Comment by Bartuzen** [comment]
I just tested it, and it works fine on qBittorrent 4.5.0 but not on 4.6.0. I believe this is a qBittorrent error, but I will try to pinpoint the issue.

**Comment by Matth7878** [comment]
Sorry to bother but as issue as been closed 3 weeks ago is there any plan to release a bug fix (or normal) version ? If not it's ok of course. It's just really annoying to constantly have to specifically change settings so it respects default.

**Comment by Bartuzen** [comment]
I'll try to make a new release today.
