### ISSUE TITLE
`Connection Timed Out` on overloaded instances

### ISSUE THREAD

**Issue by bill88t** [Bartuzen/qBitController#11]
### Bug description

I am literally running a qbittorrent container on a Raspberry Pi Zero 2W.
It is fine as by itself, it can seed at no power cost.
Sure having 50 torrents causes the web ui to take about 30s to load and that is fine.
qBitController though ain't happy with it.
The timeout threshold is too small for that.

### qBitController version

0.1.1

### qBittorrent version

4.5.0

### Android version

12

### Additional details

I propose that a timeout limit setting is made available through settings or just it being increased.

**Comment by Bartuzen** [comment]
Allowing users to set timeout limit from settings seems to be a good idea.
