### ISSUE TITLE
Opening an RSS feed crashes the app 

### ISSUE THREAD

**Issue by dan195794** [Bartuzen/qBitController#111]
Bug description
The title 

Logs
No response

qBitController version
0.8.2

qBittorrent version
4.5.0 Arm Debian

Android version
13

Additional details
No response

**Comment by Bartuzen** [comment]
I can't reproduce this, can you send crash logs?

**Comment by dan195794** [comment]
> I can't reproduce this, can you send crash logs?

Where do I get them?

Recorded it:
https://youtube.com/shorts/lG7x4VdohgI?si=HA7vJZm426KwPfRm

**Comment by Bartuzen** [comment]
You can download adb and use `adb logcat` command to get your phone's logs. It's a bit of a tedius task though, you may contact me again if you need help.

**Comment by Bartuzen** [comment]
Closing this issue because it's inactive and I can't reproduce it.
