### ISSUE TITLE
Default torrent management mode not detected properly

### ISSUE THREAD

**Issue by bill88t** [Bartuzen/qBitController#112]
### Bug description

When adding a torrent, the torrent management box in the app is set to "Default".
On my server, the default torrent management mode is "Automatic".
However the app ends up adding it as "Manual".

### Logs

N/A

### qBitController version

0.8.2

### qBittorrent version

4.6.2

### Android version

13

### Additional details

The "Download path" checkbox isn't locked when it's left on default.

**Comment by Bartuzen** [comment]
#108

**Comment by bill88t** [comment]
Whoops! Sorry for the dupe.
