### ISSUE TITLE
Error popup after update

### ISSUE THREAD

**Issue by WanderMax** [Bartuzen/qBitController#115]
unknown error: MissingFieldException Fields

[infohash_ v1, infohash _v2, download, path]

are required for type with serial name

'dev.bartuzen.qbitcontroller.model. Torrent', but theywere missing at path: $. torrents['00b9c8d0e205c073bb3f7dacabbfbacef07da232']

updated latest release, but pop-up error above when I try to connect my remote NAS  server.

previous version works fine before.

**Comment by Bartuzen** [comment]
Where does this error occur? Is it on the main screen?

**Comment by WanderMax** [comment]
![Screenshot_20240107-081156260](https://github.com/Bartuzen/qBitController/assets/15909056/b95d61e5-c2aa-4855-ba63-8bd2f350356e)
snap as above.

**Comment by Bartuzen** [comment]
What is your qBittorrent version?

**Comment by WanderMax** [comment]
RSS works fine, remote server connect ok in test.

**Comment by Bartuzen** [comment]
This is qBitController version. I was asking about qBittorrent version.

**Comment by WanderMax** [comment]
qBittorrent/4.3.9

**Comment by Bartuzen** [comment]
I fixed this issue, but I found more problems after installing your qBittorrent version. I'll try to fix them tomorrow and release a new update.

**Comment by WanderMax** [comment]
Thanks very much!

**Comment by tarkeez** [comment]
> I fixed this issue, but I found more problems after installing your qBittorrent version. I'll try to fix them tomorrow and release a new update.

I have this issue on qbittorrent 4.2.5 on anything later than qbitcontroller 0.8.2.

In my case the missing fields according to the error message are [seeding_time, tracker_count]

**Comment by Bartuzen** [comment]
I reversed big internal changes I had made because they were causing issues, so it should be fixed in the next update.
