### ISSUE TITLE
Exception on startup since v0.8.4: JSONDecodingException

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [Bartuzen/qBitController#116]
### Bug description

![screenshot](https://github.com/Bartuzen/qBitController/assets/58656153/227bddea-a06d-4369-8a3f-118feb7cc40c)

### qBitController version

0.8.4

### qBittorrent version

4.6.2.10

### Android version

13

**Comment by Bartuzen** [comment]
Are you using qBittorrent Enhanced Edition? Because there is no qBittorrent 4.6.2.10.

**Comment by FZXizzbKv7jg** [comment]
Yes, correct. qb-nox enhanced edition.

**Comment by Bartuzen** [comment]
Just to make sure, can you test [this](https://github.com/Bartuzen/qBitController/actions/runs/7451559451/artifacts/1154823193) build? Because I couldn't reproduce the problem.

**Comment by FZXizzbKv7jg** [comment]
Just tested the build. It's fixed. The error no longer occurs.
