### ISSUE TITLE
MissingFieldException error after last update

### ISSUE THREAD

**Issue by FreddyZar** [Bartuzen/qBitController#117]
### Bug description

Hi Bartu 

Been using qBitController for a few months without any problems, and a few days ago a new update came out and since then I just get a error when trying to view my torrents.

![Screenshot_20240111_205750_qBitController](https://github.com/Bartuzen/qBitController/assets/32035834/29d6e2ed-a311-4c35-9319-1bb6d33efd0c)

### qBitController version

0.8.4

### qBittorrent version

qbittorrent-nox on raspberry pi os

### Android version

13

**Comment by Bartuzen** [comment]
Should be fixed with 2e21133a08c82ba4f91d16bc4f3847e4fdce4f92.
