### ISSUE TITLE
Torrent share limits not being applied. 

### ISSUE THREAD

**Issue by saberblaze** [Bartuzen/qBitController#119]
### Bug description

After updating to 4.6.2 from 4.5.5, when applying a different share limit in the app, it states the change was made successfully but the torrent share limit for the torrent remains the same. I have to go into the web ui from a browser to change it. 

### qBitController version

0.8.4

### qBittorrent version

4.6.2 nox

### Android version

10

**Comment by Bartuzen** [comment]
`setShareLimits` now require `inactiveSeedingTimeLimit` parameter, so it fails. Also app says options are updated successfully even though server returns an error, so that's another problem.
