### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by xmha97** [Bartuzen/qBitController#12]
Please add this app to F-Droid.
Thanks.

**Comment by Bartuzen** [comment]
I requested for the app be added to F-Droid [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12301), it should be added when they test the app.

**Comment by xmha97** [comment]
Thanks.

**Comment by Bartuzen** [comment]
It's finally added to F-Droid: https://f-droid.org/en/packages/dev.bartuzen.qbitcontroller/
