### ISSUE TITLE
JsonDecodingException (Unexpected JSON token) with qB v4.6.2

### ISSUE THREAD

**Issue by m6man** [Bartuzen/qBitController#124]
### Bug description

![image](https://github.com/Bartuzen/qBitController/assets/108614717/d4eae9c4-483e-427d-90b4-e25396002914)

### Logs

Execution logs doesn't have any new entries related to this bug

### qBitController version

0.8.4

### qBittorrent version

4.6.2

### Android version

12

**Comment by Bartuzen** [comment]
This is fixed with 2e21133a08c82ba4f91d16bc4f3847e4fdce4f92.
