### ISSUE TITLE
Upload speeds not automatically refreshing in peer node list

### ISSUE THREAD

**Issue by qwqcwcawa** [Bartuzen/qBitController#127]
### Bug description

Version 0.8.5 added the feature to display the current upload and download speeds in the peer node list. However, I found that when using it, it does not automatically refresh like the speed display on the homepage. It only displays a speed that does not automatically change, and manual refresh by pulling down also does not make the numbers change. Is this a bug?

https://github.com/Bartuzen/qBitController/assets/156668576/1091a300-e914-4fdf-99e6-79c1ef6280c6

### qBitController version

0.8.5

### qBittorrent version

qBittorrent Enhanced Edition v4.6.3.10

### Android version

13

**Comment by Bartuzen** [comment]
That's an oversight on my end. I will fix it very soon.
