### ISSUE TITLE
No ability to use categories or tags in the Add Torrent page 

### ISSUE THREAD

**Issue by Kirillbzp** [Bartuzen/qBitController#128]
### Bug description

There are only the labels "Category" and "Tags".  It is not possible to add an existing category.  It will be enough to add a new torrent and only then change the category.  And if the storage path is tied to the category, then in order not to move it, I have to add the torrent without starting it and start it manually after changing the category 
![Screenshot_2024-03-09-21-40-09-988_dev bartuzen qbitcontroller](https://github.com/Bartuzen/qBitController/assets/3366363/3746c873-6aaa-49a0-962f-67f52478b40e)

### qBitController version

0.8.5

### qBittorrent version

4.1.7

### Android version

14

**Comment by Bartuzen** [comment]
I haven't checked yet, but it's likely that your version of qBittorrent doesn't have endpoints for them. If that's the case, you need to update qBittorrent.

**Comment by Kirillbzp** [comment]
Yeah, I had Ubuntu 20.04. But on this version, the maximum available qBittorrent package was 4.1.7. After updating Ubuntu to version 22.04, the qBittorrent 4.4.1 package became available, and as you said, the selection of categories when adding a torrent worked.
As if the main problem is solved. Thank you
