### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by zt64** [Bartuzen/qBitController#133]
### Describe your suggested feature

Hi, as the title suggests I am requesting that the app be updated to follow Material You design. I will try to implement it myself even and open a pull request but I first wanna check with you @Bartuzen if a complete UI redesign would be okay

### Additional details

I would also like to ask about the possibility of considering migrating to Jetpack Compose. It would take more work. I am however quite familiar with it

**Comment by Bartuzen** [comment]
Updating to Material You is a great idea. If you implement it and submit a PR, I'd accept it.
As for migrating to Jetpack Compose, it's going to take more work. But if you go for it, I'm fine with it.
