### ISSUE TITLE
Search Online feature not working

### ISSUE THREAD

**Issue by miguel-mpm** [Bartuzen/qBitController#140]
### Bug description

When trying to use a search plugin, I get a 404 error in the app ("Api returned an error: 404"). 

Same search works fine from the WebUI

I have only 1 search plugin enabled: ThePirateBay. You can find it in the Qbittorrent's github list of [unofficial search plugins](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins).

### qBitController version

0.8.5

### qBittorrent version

4.5.2

### Android version

12

**Comment by Bartuzen** [comment]
This looks like the same issue as #132. I can't reproduce the problem, it's working fine for me.
