### ISSUE TITLE
 the top color can be customized, or add a pure white theme

### ISSUE THREAD

**Issue by mxm012337** [Bartuzen/qBitController#142]
### Describe your suggested feature

Sorry, I don't speak English, this is the result of using the translation software, the top color can be customized, or add a pure white theme

**Comment by Bartuzen** [comment]
If I understood correctly, you want the top app bar to be white. I've updated the app to use Material Design 3, which includes this change, but I haven't released the new version yet. So, the top app bar is now white. If I've misunderstood your request, please feel free to reopen the issue. Here's how it currently looks:
![image](https://github.com/user-attachments/assets/1686da2a-4719-4b2a-8658-8c161ac6f688)

**Comment by mxm012337** [comment]
> If I understood correctly, you want the top app bar to be white. I've updated the app to use Material Design 3, which includes this change, but I haven't released the new version yet. So, the top app bar is now white. If I've misunderstood your request, please feel free to reopen the issue. Here's how it currently looks: ![image](https://private-user-images.githubusercontent.com/15032958/355342306-1686da2a-4719-4b2a-8658-8c161ac6f688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzM2MDAsIm5iZiI6MTcyMjkzMzMwMCwicGF0aCI6Ii8xNTAzMjk1OC8zNTUzNDIzMDYtMTY4NmRhMmEtNDcxOS00YjJhLTg2NTgtOGMxNjFhYzZmNjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA4MzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZTM4ZTI0NDRkZjU3ZmE1ZDAyMmU1NmY1MDZhMTM3YjZlN2VlZjZmZWJiYjE2OGU4NThmN2IxYjk0NDA2YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.llPKF4qEF5Rd6IO295do3ROInDxCzKlMG-7MJ6PE_EE)

Yes, that's it. I wonder what can be done to release a new version?

**Comment by Bartuzen** [comment]
I'm hoping to release a new version this month, but I can't guarantee it.
