### ISSUE TITLE
weird line break

### ISSUE THREAD

**Issue by ixff** [Bartuzen/qBitController#149]
### Bug description

line break at wrong place when the title includes Chinese.

![Screenshot_2024-09-14-21-17-18-033_dev bartuzen qbitcontroller-edit](https://github.com/user-attachments/assets/d3b15ea7-7db2-43bc-9e82-bcd8fb9f4e15)

### qBitController version

1.0.0

### qBittorrent version

4.6.6

### Android version

13

**Comment by WanderMax** [comment]
still exists in version 1.10

**Comment by Bartuzen** [comment]
I tested different line break options, but none of them fully resolved the issue. I also tested a few Android and desktop apps, and this problem seems quite common. So, it's either intended behavior or a bug in the text renderers. In that case, I can't fix the issue.
