### ISSUE TITLE
Torrents list not updating since 1.0.0

### ISSUE THREAD

**Issue by Matth7878** [Bartuzen/qBitController#150]
### Bug description

Torrents list doesn't seem to update anymore.
When opening app no torrents are listed before forcing an update with a swipe down.
Afterwards same no automatic update. Forcing update is needed to refresh.

### qBitController version

1.0.0

### qBittorrent version

4.6.6

### Android version

14

### Additional details

Refresh set to 2 secs. Tried setting it to 20 secs and no difference.
Before updating to latest release no problem.

**Comment by Bartuzen** [comment]
I can confirm this issue occurs when the app is left in the background and reopened later, after process death. Just to clarify, the issue doesn't happen if you remove the app from recents and relaunch it, correct?

**Comment by Matth7878** [comment]
Yes it's correct.
I just tested after force closing app then reopening it and it seems to work correctly. When pausing a torrent list is updated soon after and I confirm I see activity for some of my torrents
