### ISSUE TITLE
Filtering Active torrents can not be saved

### ISSUE THREAD

**Issue by zhufeng** [Bartuzen/qBitController#153]
### Describe your suggested feature

When filtering torrents Status "Active" then exit app, open app again it always load torrents Status to "All". 

This is needed because when many torrents(>1000) added to qb, webui's loading performance is quite low, and filtering only active torrent can be much more faster.

By the way , for v1.0.0 the new Material Design3/You theme, is it able to customize theme color?

**Comment by Bartuzen** [comment]
I can add an option to set default filtering.
As for colors, on Android 12 and above, the app uses system colors. Currently, there’s no way to change colors on versions below Android 12. I may add an option for that after fully migrating to Compose, but it will take some time.
