### ISSUE TITLE
[BUG] - the “pause” action no longer works with the new version of qBittorrent (5.0.0)

### ISSUE THREAD

**Issue by pierrejo** [Bartuzen/qBitController#154]
### Bug description

the “pause” action no longer exists in the new version (5.0.0) of qBittorrent. It's now “stop”. This means you can no longer pause and/or stop your torrents.

### Logs

Message : "The api returned an error: 404"

### qBitController version

1.0.0

### qBittorrent version

5.0.0

### Android version

14

### Additional details

I've been using the app for over a year and it's a real pleasure to be able to control my torrents with it. Thanks again for all your hard work and the graphical overhaul on the latest version!

**Comment by Bartuzen** [comment]
I fixed this yesterday. I will try to release a new version today.

**Comment by teaalltr** [comment]
I can confirm, fixed in 1.1.0.
fDroid repos is still on 1.0.0, ti should be updated there I guess (probably fDroid's fault).

Thanks @Bartuzen for your amazing app!
