### ISSUE TITLE
can't pause/resume an existing torrent

### ISSUE THREAD

**Issue by ixff** [Bartuzen/qBitController#156]
### Bug description

> API returned an error: 404

### qBitController version

1.1.0

### qBittorrent version

4.6.6

### Android version

13

**Comment by Bartuzen** [comment]
Did you downgrade qBittorrent? qBitController 1.1.0 caches the qBittorrent version for an hour, so waiting or restarting the app should refresh the version and resolve the issue.

**Comment by Bartuzen** [comment]
I think qBitController fails to retrieve or parse qBittorrent version so it assumes 5.0.0 by default, but I have no idea why it happens.

**Comment by Bartuzen** [comment]
For qBittorrent 5 support, you need to update qBitController to version 1.1.0. However, this version is currently unavailable on F-Droid due to issue #63.
