### ISSUE TITLE
The delete torrent + "also delete files" function isn't working with new versions of qbittorrent.

### ISSUE THREAD

**Issue by dessalines** [Bartuzen/qBitController#158]
### Bug description

This used to work, but since my qbittorrent backend upgraded recently, it stopped working, and I have to manually remove the files from the hard drive.

- hold and click to delete torrent
- click also delete files
- Files are still there on the HD

### Logs

NA

### qBitController version

1.1.0

### qBittorrent version

v5.0.0

### Android version

14

### Additional details

NA

**Comment by Bartuzen** [comment]
I can't replicate this issue. Can you try testing it with the WebUI?

**Comment by dessalines** [comment]
My bad! qbittorrent decided to make it not delete anything by default (just move it to a trash can, which doesn't exist for any docker setup).

https://github.com/binhex/arch-qbittorrentvpn/issues/272
