### ISSUE TITLE
Support user added certificates

### ISSUE THREAD

**Issue by DUOLabs333** [Bartuzen/qBitController#16]
Alternatively, use the OS trust store (my custom CA is saved there, and other apps can connect to sites with certificates signed by my CA, but this app says `Trust anchor for certification path not found`.

**Comment by Bartuzen** [comment]
The option to trust self-signed certificates has been added since the latest release. However, I will add support for user added certificates.

**Comment by DUOLabs333** [comment]
If you mean 0.3.0, I don't see the option.

**Comment by Bartuzen** [comment]
It was added after 0.3.0, so it will be in next version.
