### ISSUE TITLE
Let's Encrypt certificate not recognized

### ISSUE THREAD

**Issue by colemar** [Bartuzen/qBitController#169]
### Bug description

`Trust anchor for certification path not found` when testing HTTPS connection to my qbittorrent-nox server which is using a Let's Encrypt certificate.
Chrome and other browsers do not complain about the certificate.

Workaround (not ideal): Check `Trust self-signed certificates` when adding a new server.

### qBitController version

1.1.0

### qBittorrent version

5.0.1

### Android version

14

**Comment by Bartuzen** [comment]
I tested this using valid test websites listed on [Let's Encrypt's Certificates Page](https://letsencrypt.org/certificates/) under the Root CAs section. The site under ISRG Root X1 was working, but the one under ISRG Root X2 produced the same error.
To solve this, I downloaded the PEM file from the ISRG Root X2 section and added it through the system settings, which resolved the issue. Can you also try this and see if it solves the issue for you?

**Comment by colemar** [comment]
No, loading ISRG Root X2 pem file through the system settings did not solve the issue.

But I noticed that **curl** had a similar problem when testing the https connection to my qBittorrent server. I tested **curl** also against my Apache web server (same domain name) and it worked OK.
Then I realized that the Apache server was configured to read `/etc/letsencrypt/live/mydomain.tv/fullchain.pem` while qBittorrent.conf contained `WebUI\HTTPS\CertificatePath=/etc/letsencrypt/live/mydomain.tv/cert.pem`.
I pointed qBittorrent to `fullchain.pem` and it worked. Also **curl** does not complain anymore.
