### ISSUE TITLE
Issue with connection 

### ISSUE THREAD

**Issue by codeXXjs** [Bartuzen/qBitController#17]
### Bug description

Good Sir,
I have to address something. There is a bug that doesn't let me connect to my pc sometimes. I have to retry it over and over again (10+ attempts). Can you please look into this issue. My internet connection is very stable.
Thank you in advance. 

### qBitController version

0.3.0

### qBittorrent version

v4.5.0.10 and older 

### Android version

11

**Comment by Bartuzen** [comment]
Can you give more details? Are you getting a timeout error, or is it something else? Does WebUI work when you connect from a web browser?

**Comment by codeXXjs** [comment]
Yes, I am getting connection timeout error. But after 10+ retries it connects again. I believe there is a delay in signing in with the client. My internet connection is working perfectly fine (50mbps)

![screenshot](https://user-images.githubusercontent.com/118744203/210828384-74d2c8a9-e65e-4711-a362-cb2858dd4fe8.jpg)

**Comment by Bartuzen** [comment]
Could it be that you have set connection timeout to a very low value? Try increasing it. If that doesn't work, the app tries to login multiple times at startup. Even though I haven't observed any problems with it, maybe this could be the issue. We can try again after I fix that problem.

**Comment by codeXXjs** [comment]
Here with an update,
I cleared all data and reinstalled the app. Somehow its working fine now. No connection timeout. 
Also, I really like your app. Been using it for 2 weeks now. I have tired other qBittorrent (remote client) mobile and nothing comes close to what you have made (Desktop like experience).

Thank you so much again Sir
