### ISSUE TITLE
drawer width too wide 

### ISSUE THREAD

**Issue by WanderMax** [Bartuzen/qBitController#171]
drawer width is too wide.
 v0.85  vs v1.10

**Comment by WanderMax** [comment]
![Screenshot_20241117-190258212](https://github.com/user-attachments/assets/7c53c80a-c63d-471a-9d44-f74e622361b2)
![Screenshot_20241117-190309718](https://github.com/user-attachments/assets/43b4d1ea-ce94-4a3a-ac08-8c367e2f1964)

**Comment by Bartuzen** [comment]
This is intended, as that's the default width of the navigation drawer in Material Design 3.
