### ISSUE TITLE
"Start Torrent" checkbox does not work

### ISSUE THREAD

**Issue by grahamgrieb** [Bartuzen/qBitController#172]
### Bug description

Unchecking the "Start Torrent" checkbox when adding a torrent does not stop the torrent from automatically starting. The torrent will immediately start downloading  even with it unchecked.

### qBitController version

1.1.0

### qBittorrent version

5.0.2

### Android version

14

**Comment by Bartuzen** [comment]
Fixed with 7e06697cc488373eb9d34947c5b7db9e865e83e1. It will be available on the next version.
