### ISSUE TITLE
Add sorting direction ⬆️⬇️

### ISSUE THREAD

**Issue by AdamSchuttovits** [Bartuzen/qBitController#173]
### Describe your suggested feature

In many cases you want to order the torrents in a descending order. For example if you have a long list of torrents and you want to see newest first, you sort it by "date added desc".
Please add sorting direction

**Comment by Bartuzen** [comment]
If you scroll down the sorting menu, there is an option to reverse the sorting.

**Comment by AdamSchuttovits** [comment]
That's the most I can scroll down on my Pixel 8a:
![Screenshot_20241130-083607.png](https://github.com/user-attachments/assets/83ddf752-22c1-4cc2-92fd-d4982380c6c4)

**Comment by Bartuzen** [comment]
I can't reproduce this issue. I will investigate it.

**Comment by AdamSchuttovits** [comment]
That's the most I can scroll down on my Pixel 8a:
![Picsart_24-11-30_08-53-51-769.png](https://github.com/user-attachments/assets/9f4350d6-12d7-4a20-ade8-d66bcb75a865)

**Comment by AdamSchuttovits** [comment]
Thank you for investigating it!

**Comment by AdamSchuttovits** [comment]
It has to do something with the display size and font size settings. If I set up the smallest size settings for both, the Reverse checkbox becomes visible:
![Screenshot_20241206-080050.png](https://github.com/user-attachments/assets/d849daa8-8ec9-49c2-83e5-46960560fa84)

![Screenshot_20241206-080037.png](https://github.com/user-attachments/assets/d98d1ee1-6c72-4406-83d1-eb95dbf9fa9e)

**Comment by AdamSchuttovits** [comment]
Created a bug ticket for it:
#174
