### ISSUE TITLE
View ratio and upload stats for each torrent 

### ISSUE THREAD

**Issue by remisharrock** [Bartuzen/qBitController#18]
Hi @Bartuzen ! Thanks for this great app !
I was wondering if it is possible to add the ratio and upload statistics for each torrent.
Thank you!

**Comment by remisharrock** [comment]
I think it is related to this commit:
https://github.com/Bartuzen/qBitController/commit/7ce060f64e76218f86a3169939f3c87e9567f054
Just saw that ! So I guess it will be released soon!

**Comment by Bartuzen** [comment]
Exactly, it will be on the next version.
