### ISSUE TITLE
Status color / tag

### ISSUE THREAD

**Issue by Matth7878** [Bartuzen/qBitController#31]
### Describe your suggested feature

Love the app. Now that I use it almost exclusively there is some UI improvement that would be nice. I am going to open issues for them. This one is my first.

In main screen it would be nice to show status with color or even better like little tags having different colors depending on the status? (Downloading could be green, seeding orange, finished/completed or paused grey)
Right now it's kind of difficult to tell status with just a glance.

Same for torrent files list. For the priority / status a little colored tag would be nice and it would be easier to see if your file is set to not download (grey tag for instance) or if not then juste use a green tag.
Here tapping the tag could be used as a shortcut to change priority.

**Comment by Bartuzen** [comment]
I was going to implement this by changing color of progress bar. But for some reason, it's very tedious to change its color. I will implement this, but I'm not sure how I'll do it yet.
