### ISSUE TITLE
Screen flickering on refresh

### ISSUE THREAD

**Issue by Matth7878** [Bartuzen/qBitController#33]
### Bug description

Maybe you already planned to correct it or decided it was not worth it as it is a minor issue but when UI is refreshing the screen flicker.
It's more noticeable with a short refresh interval. (Mine is set to 2 sec)

### qBitController version

0.5.0

### qBittorrent version

4.5.0 windows

### Android version

11

**Comment by Bartuzen** [comment]
This is actually a feature of ListAdapter, items flicker when their contents change. But I agree, its quite annoying to look at. Disabling it for torrent list seems like the best option.
