### ISSUE TITLE
Filter in upload torrent

### ISSUE THREAD

**Issue by buongiorgio** [Bartuzen/qBitController#36]
I have many seeding torrents, but usually just a couple are actually sending data and is difficult to locate them (only solution I came up with is sorting seeding torrents by speed), I think it would be handy to have the possibility to filter torrents by "in upload" status.

**Comment by Bartuzen** [comment]
I think adding active and inactive filters would be a better option, like in qBittorrent.

**Comment by buongiorgio** [comment]
Well, any name will work as long the result is the same 😄
