### ISSUE TITLE
Connection issues with 0.5.0+

### ISSUE THREAD

**Issue by CommanderBubble** [Bartuzen/qBitController#37]
### Bug description

After updating from 0.4.0, and having it installed for a day or so, i am no longer able to make a connection - i get a timeout/refusal of credentials

the web access if still fine, and if i downgrade to 0.4.0, this issue does not happen - i've had it installed for over a week and this doesn't happen, whereas with 0.5.0+ (tried with 0.5.1 as well) after a day or two this issue reoccurs

### qBitController version

0.5.0+

### qBittorrent version

4.4.5

### Android version

13

**Comment by CommanderBubble** [comment]
seems similar to #35, possible duplicate issue?

**Comment by Bartuzen** [comment]
On #35, you get invalid credentials error if app is left open for an hour (or whatever you set as session timeout on qBittorrrent). It works fine in the first hour. Is this similar to your problem?

**Comment by CommanderBubble** [comment]
no, i haven't left the session open AFAIK, i've just exited the app and tried to add something at another time. i'll update it and see what happens.

**Comment by Bartuzen** [comment]
If you left app open in the background when you left, then it is highly likely that this is same as #35. I'm closing this issue as duplicate for now. If you think it isn't duplicate, please let me know.

**Comment by CommanderBubble** [comment]
yes, it does appear to be the same as #35
