### ISSUE TITLE
Disabling notifications

### ISSUE THREAD

**Issue by vodkapmp** [Bartuzen/qBitController#55]
### Describe your suggested feature
A toggle or other way to disable the notification feature.

The new notification feature has no way to disable it, I've tried setting the check interval to 0, which changes to 1.

**Comment by vodkapmp** [comment]
That is a good point, I should've thought of that.
Will the check still run if you disable notifications? It wouldn't be much of a battery use, but still some unnecessary use if so.

**Comment by Bartuzen** [comment]
> Will the check still run if you disable notifications?
No, the worker is stopped if notifications are disabled. It won't run in the background.

**Comment by vodkapmp** [comment]
Perfect then, I'll just close this issue.
Thanks for the info!

**Comment by kattjevfel** [comment]
I have notifications turned off and yet it's using a ton of data in the background, should I make a new issue?
![Screenshot_20240731-124215_Settings](https://github.com/user-attachments/assets/27719bed-2abe-4aac-a713-712f5c386fe3)

**Comment by Bartuzen** [comment]
Yes, you can create a new issue.
