### ISSUE TITLE
IllegalArgumentException error

### ISSUE THREAD

**Issue by quamok** [Bartuzen/qBitController#57]
### Bug description

When loading the torrent screen, I get an error for specific torrents:

Unknown error: IllegalArgumentException Illegal character in query.

It may be related to the pipe character in the passkey. Please see screenshot for reference.

![2023-03-31_16-44](https://user-images.githubusercontent.com/24906799/229227013-a7f0924a-4a30-4432-a526-08f33076bbe9.png)

### qBitController version

0.7.0

### qBittorrent version

4.3.9

### Android version

13

**Comment by Bartuzen** [comment]
Since this is a pretty major issue, I will release an update to fix it soon.

**Comment by FZXizzbKv7jg** [comment]
Now there's

`Unknown error: NullPointerException formattedTracker must not be null.`

**Comment by Bartuzen** [comment]
I've just commited 34df83cbb3fabaad594d08ef86003cf2b43b5581, which should fix it.
