### ISSUE TITLE
Quick way to pause/resume a torrent, like gestures, context menu or a toggle?

### ISSUE THREAD

**Issue by Pentaphon** [Bartuzen/qBitController#58]
### Describe your suggested feature

Right now we have to press and hold a torrent and then we have to get our finger up all the way to the top right of our (sometimes big and very tall) phones to press the buttons at the top right so can we have a quick way to pause and resume torrents on the list without having to move our finger to the top right each time? Either of the following would be great.

1) A play/pause button on each torrent on the list

2) A simple swipe right to pause and swipe right again to resume gesture that can be done on any torrent in the list. 

3) Press and hold to open a small context menu by your finger with extra commands?

Or whatever solution to make this happen with as little finger movement as possible you have in mind?

Thanks. 

P.S. 0.7.0 has been awesome to use so far.

**Comment by Bartuzen** [comment]
Second option seems the most viable one. We can even implement delete gesture in the other direction.

**Comment by Pentaphon** [comment]
> Second option seems the most viable one. We can even implement delete gesture in the other direction.

You could also make those swipe gestures optional for people that don't want gestures, similar to how optional gestures are in email clients that mark read and delete emails. I personally like the gesture solution. You may want to add a confirmation after a left swipe to delete to make sure people can't delete their torrents by mistake.
