### ISSUE TITLE
NullPointerException formattedTracker must not be null

### ISSUE THREAD

**Issue by dm1sh** [Bartuzen/qBitController#61]
### Bug description

Despite I'm on 0.7.1, I still get this error on main screen.

### Logs

Unknown error: NullPointerException formattedTracker must not be null.

### qBitController version

0.7.1

### qBittorrent version

4.5.2

### Android version

13

**Comment by Bartuzen** [comment]
This is fixed in 34df83cbb3fabaad594d08ef86003cf2b43b5581, after 0.7.1 is released. I will try to release a new update today that includes the fix.
