### ISSUE TITLE
Unknown error: ProtocolException unexpected end of stream

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [Bartuzen/qBitController#64]
### Bug description

The error sometimes occurs (starting the app / refresh). The app continues connecting to the server.

### qBitController version

0.7.2

### qBittorrent version

qBittorrent Enhanced Edition v4.5.2.10

### Android version

13

**Comment by Bartuzen** [comment]
I can't reproduce this issue, and I have no idea what the problem is. There isn't much I can do in this situation.
