### ISSUE TITLE
Make progress bar and it's related info identical in torrents list and torrent details

### ISSUE THREAD

**Issue by Matth7878** [Bartuzen/qBitController#68]
### Describe your suggested feature

In torrents list there is a progress bar for each torrents.
The progress bar is also present for torrent details. (The screen you go when tapping one of the torrent in the list)

It would be nice if both progress bar were the same. Currently they are not : progress bar in torrent details is missing ratio.

**Comment by Bartuzen** [comment]
I hadn't done that because ratio was already displayed below, but I guess making it consistent would be better.
