### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by InvisibleRain** [Bartuzen/qBitController#76]
### Describe your suggested feature

Support for languages other than English would be awesome. Additionally, I would be more than happy to commit some translations to the project's Weblate or any similar platform

**Comment by Bartuzen** [comment]
In order to use a translation website, I have to first organize the localization file since it's very disorganized. Once I've done that, I plan on setting up one.

**Comment by Bartuzen** [comment]
I set up a Weblate project, you can access it [here](https://hosted.weblate.org/projects/qbitcontroller/). I will close this issue once the project is approved.

**Comment by WanderMax** [comment]
for open source project, you can try crowdin, it's free.

**Comment by Bartuzen** [comment]
I've just tried Crowdin, and it seems like a much better option. I'll consider switching to it.

**Comment by Bartuzen** [comment]
I've set up a Crowdin project and applied for Open Source License, which was approved in an hour. Once I finish configuring it, I will update the README and close the issue.

**Comment by comradekingu** [comment]
Crowdin is only unpaid for non-commercial open source projects.
It is an absolute pain to use, and it never goes well.

**Comment by Bartuzen** [comment]
After testing them out, it seems that they both have pros and cons. However, I'm more inclined towards Weblate since it's open-source. We still need to wait for project approval though.
