### ISSUE TITLE
Tags are not applied from "add torrent" menu. 

### ISSUE THREAD

**Issue by FAT9L** [Bartuzen/qBitController#77]
### Bug description

When adding a new torrent (main overview > "+" icon) and selecting a file to add, options are given to select categories and/or tags. 

Categories are correctly assigned to these added torrents, but tags are not. 

The tag must be manually added afterward, by selecting it from the overview page, and then selecting "set tags" from the context (3-dot) menu. 

### qBitController version

0.7.3

### qBittorrent version

4.2.5

### Android version

13

**Comment by Bartuzen** [comment]
That's because this option is added on [API v2.6.2](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#api-v262), but you are using qBittorrent 4.2.5, which uses API v2.5.1. So, you need to update qBittorrent.
