### ISSUE TITLE
Windows app

### ISSUE THREAD

**Issue by Beersteddy** [Bartuzen/qBitController#78]
### Describe your suggested feature

Been using your app for a while. It's already brilliant and only getting better.

Just wondering if ever gonna consider making windows/linux app to control qbit just like this Android app does.

To my biggest surprise, there is no such app, and qbit webui is not exactly that great.

**Comment by Bartuzen** [comment]
It's unlikely to happen because I would have to write it from scratch. Your best bet is to use 
- Windows Subsystem for Android on Windows,
- Anbox or Waydroid on Linux,
- or an Android emulator.
