### ISSUE TITLE
'Top/Bottom Jump, Server Reorder, Reverse Sort' feature requests

### ISSUE THREAD

**Issue by WanderMax** [Bartuzen/qBitController#84]
Hi,
I have some ideas as below:
1. float button that can perform list position jump, such as "jump to top" or "jump to bottom". I think it's nice when scroll among the list with hundreds of torrents.
2. server reorder, I can manually arrange the order, set one server at top.
3. reverse sort ability in sort menu.

Thanks.

**Comment by Bartuzen** [comment]
3rd one already exists. You might have to scroll if your screen isn't high enough.
Could you create separate issues for the others? It's hard to keep track of multiple issues within one.
