### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [Bartuzen/qBitController#89]
### Describe your suggested feature

https://hosted.weblate.org/projects/qbitcontroller/strings/#information
specifies GPLv3-only, whereas the repo here doesn't.

It is usually the case that people mean to select "or-later", as that grants more flexibility in bringing in or exporting code, and allows for more possible licenses to be used later, like AGPLv3, or potentially GPLv4.
(It is also possible to make it GPLv3-only if the GPLv4 turns out to be bad, so I see no downside there.)

### Additional details

It can be changed in https://hosted.weblate.org/settings/qbitcontroller/strings

**Comment by Bartuzen** [comment]
Actually, I had deleted the Weblate project (see #76). But for some reason it's still visible, and most of the operations are not working. I'll try to contact Weblate and hopefully they can solve the problem.

**Comment by comradekingu** [comment]
@Bartuzen Works just fine from here. Translated most of nb_NO just now.

**Comment by Bartuzen** [comment]
Translating seems to be working. But I can't change license, or delete components. It's stuck at updating component status.

Coincidentally, libre license has been approved at the same time you commented. Hopefully, they will also fix the other issue soon.

And lastly, thanks for your contribution!

**Comment by Bartuzen** [comment]
It seems like changing license worked even though it's still stuck at updating, so I'm closing this issue.

**Comment by Bartuzen** [comment]
The project has been finally deleted, so I created a new one. But it's still broken, I can't add translations. So we still have to wait for Weblate to fix it.
Also, I had backed up the translations, so your progress isn't lost.

**Comment by Bartuzen** [comment]
The problem seems to be solved. I think there was a problem with whole Weblate, because the servers went for a minute and everything is working fine now.
Anyway, I'm uploading your translations here so that you can upload them to Weblate under your name: [strings.zip](https://github.com/Bartuzen/qBitController/files/11865304/strings.zip)
