### ISSUE TITLE
Auto ban Leech clients (XunLei, XL00**, XL0.0.*.* etc)

### ISSUE THREAD

**Issue by predb** [Bartuzen/qBitController#91]
### Describe your suggested feature

As we know, XunLei (also known as: Thunder, XL0012, XL0018, etc) and some other clients only leech from others but never upload, And the client XunLei from China has a huge user base, Its behavior and large user base have caused trouble for many people.

I heard that it is possible to realize auto-ban function based on qb's Web UI, Do you have any plan in this? 
thanks.

**Comment by Bartuzen** [comment]
I'm not sure if I understood you correctly, do you want some clients to be automatically banned? If so, that's out of the scope for this app. You may try [qBittorrent Enhanced](https://github.com/c0re100/qBittorrent-Enhanced-Edition), which supports this.
