### ISSUE TITLE
Add Country Flags to Peer List

### ISSUE THREAD

**Issue by RecursiveRegistrations** [Bartuzen/qBitController#94]
### Describe your suggested feature

I would really like it if the Peer List in the app showed the country flag associated with each peer just like qBittorrent does when you access it directly. I realize that functionally, this doesn't add any features to the app, but I really like seeing the flags and would love to be able to see them in the app.

### Additional details

There are two ways that I can think of for how to add country flags to the app.

The first approach is obviously to bundle the flag icons into the app and load the appropriate flag from the app resources for each peer.

The second approach is to rely on the qBittorrent web server to provide the flags that are displayed. The qBittorrent web server serves the flag icons from `http://localhost:8080/images/flags/<ISO 3166-1 alpha-2 code>.svg` where `<ISO 3166-1 alpha-2 code>` refers to the [ISO 3166-1 alpha-2 country code standard](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements). For example, the United States flag is located at `http://localhost:8080/images/flags/us.svg`. Since this app relies on accessing a qBittorrent server to provide any meaningful functionality, I think it would probably be fine to rely on it to provide the flags that are displayed.

**Comment by RecursiveRegistrations** [comment]
Awesome! Thank you so much! Do you think you'd be fine with a happy medium of fetching the flags from the qBittorrent server and caching any flags that have been accessed? I think that would be a really nice tradeoff between keeping the app size low while also reducing redundant network activity.

**Comment by Bartuzen** [comment]
Yep, that's exactly what I was thinking.

**Comment by RecursiveRegistrations** [comment]
Awesome! Thank you!
