### ISSUE TITLE
Clickable links in torrent comments 

### ISSUE THREAD

**Issue by kattjevfel** [Bartuzen/qBitController#98]
### Describe your suggested feature

Torrents often include links in their comment, linking to the page it was downloaded from etc. In at least the webui they're clickable and I'd love if that were the case in this app too.

### Additional details

![Screenshot_20230906-073826_qBitController](https://github.com/Bartuzen/qBitController/assets/6226312/347b6672-1451-4035-9a60-89b4dd3e4be6)

**Comment by kattjevfel** [comment]
wow that was fast, thanks!

**Comment by dm1sh** [comment]
New UI introduced regression on this feature. Could you enable autoLink property again, please

**Comment by dm1sh** [comment]
> I already fixed it since the last update, though I had to use a third-party library since Compose doesn't have auto link
Great, thanks. I think is useful enough to go with the dependency
